name: Build

on: 
  push:
  #  branches: 
  #    - main
  workflow_dispatch:
  
jobs:
  linux_gcc:
    name: Build Linux GCC
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3
            
        
    - name: Install Dependencies
      run: |
        sudo dpkg --add-architecture i386
        sudo apt-get update
        sudo apt-get upgrade -y
        sudo apt-get install -y \
            binutils:i386 \
            gcc-multilib \
            g++-multilib

   
