name: Build

on: [push, pull_request]

jobs:
  linux_gcc:
    name: Build Linux GCC
    runs-on: ubuntu-20.04
    env:
      TEST: ${{ secrets.TEST }}
    steps:
    - uses: actions/checkout@v3

    - name: cache
      uses: actions/cache@v3
      with:
        path: ~/.ccache
        key: build-ccache-${{ env.GITHUB_RUN_ID }}
        restore-keys: |
          build-ccache
            
    - name: Find Path
      run: |
        pwd
        ls -al ~/
