name: Build

on: [push, pull_request]

jobs:
  linux_gcc:
    name: Build Linux GCC
    runs-on: ubuntu-20.04
    env:
      TEST: 
    steps:
    - uses: actions/checkout@v3

    - name: cache
      uses: actions/cache@v3
      with:
        path: ${{github.workspace}}/ROM
        key: build-${{github.run_id}}
        restore-keys: |
          build
            
    - name: Find Path
      run: |
        mkdir TEST
        wget -qO soh/TEST/README.md ${{ secrets.TEST }}
        ls soh/TEST/
