name: Build

on: 
  push:
  #  branches: 
  #    - main
  workflow_dispatch:
  
jobs:
  linux_gcc:
    name: Build Linux GCC
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3

    - name: cache
      uses: actions/cache@v3
      with:
        path: ${{github.workspace}}/soh/ROM
        key: build-${{github.run_id}}
        restore-keys: |
          build
          ~/.ccache
            
    - name: Prepare Build
      run: |
        if [[ ! -e soh/ROM/baserom_non_mq.z64 ]]; then
          mkdir -p soh/ROM 
          wget -qO soh/ROM/ROM.zip ${{ secrets.DEBUG_ROM }} 2>/dev/null
          7za e soh/ROM/ROM.zip -so > soh/ROM/baserom_non_mq.z64
        fi
        cp soh/ROM/baserom_non_mq.z64 soh
        
    - name: Install Dependencies
      run: |
        sudo dpkg --add-architecture i386
        sudo apt-get update
        #sudo apt --fix-broken install
        sudo apt-get install -y \
            binutils:i386 \
            gcc-10:i386 \
            g++-10:i386 \
            python \
            cmake \
            lld \
            libibus-1.0-dev:i386 \
            libpulse-dev:i386 \
            libsdl2-dev:i386 \
            zlib1g-dev:i386 \
            libbz2-dev:i386 \
            libpng-dev:i386 \
            libibus-1.0-dev:i386 \
            libpulse-dev:i386 \
            gir1.2-ibus-1.0:i386 \
            libglib2.0-dev:i386 \
            libpulse-mainloop-glib0:i386 \
            gir1.2-glib-2.0:i386 \
            libibus-1.0-5:i386 \
            libglib2.0-0:i386 \
            libmount-dev:i386 \
            libselinux1-dev:i386 \
            libmount1:i386 \
            libselinux1:i386 \
            libpcre2-dev:i386 \
            libgles2-mesa-dev
        sudo ln -s /usr/bin/gcc-10 /usr/bin/gcc
        sudo ln -s /usr/bin/gcc-10 /usr/bin/cc
        sudo ln -s /usr/bin/g++-10 /usr/bin/g++
        sudo ln -s /usr/bin/g++-10 /usr/bin/c++

    - name: Build glew:i386
      run: |
        git clone https://github.com/Perlmint/glew-cmake.git 
        cmake glew-cmake 
        make -j$(nproc) 
        make install ARCH64=false

    - name: Build SDL2:i386
      run: |
        SDL2VER=2.0.22
        if [[ ! -e ~/.ccache ]]; then
          mkdir ~/.ccache
        fi  
        cd ~/.ccache
        if [[ ! -e SDL2-${SDL2VER} ]]; then
          curl -sLO https://libsdl.org/release/SDL2-${SDL2VER}.tar.gz
          tar -xzf SDL2-${SDL2VER}.tar.gz
          cd SDL2-${SDL2VER}
          ./configure --build=i386-linux-gnu --prefix=/usr
          make && cd ../
          rm SDL2-${SDL2VER}.tar.gz
        fi
        sudo make -C SDL2-${SDL2VER} install
        sudo cp -av /lib/libSDL* /lib/i386-linux-gnu/
        
    - name: Build StormLib
      run: |
        git clone https://github.com/ladislav-zezula/StormLib external/StormLib
        cmake -B external/StormLib/build -S external/StormLib
        cmake --build external/StormLib/build
        cp external/StormLib/build/libstorm.a external
        cp /usr/local/lib/libGLEW.a external

    - name: Build libultraship
      run: make -C libultraship -j$(nproc)

    - name: Build OTRExporter
      run: make -C OTRExporter/OTRExporter -j$(nproc)

    - name: Build ZAPDTR
      run: make -C ZAPDTR -j$(nproc)

    - name: Build SOH
      run: |
        make setup -C soh -j$(nproc) 
        make -C soh -j$(nproc)

    - uses: actions/upload-artifact@v3
      with:
          name: SOH-Linux
          path: soh/soh.elf
