name: Build

on: [push, pull_request]

jobs:
  linux_gcc:
    name: Build Linux GCC
    runs-on: ubuntu-20.04
    env:
      TEST: ${{ secrets.TEST }}
    steps:
    - uses: actions/checkout@v3
    
    - name: Find Path
      run: ls -al 
